version: '3.8'

services:
  discord-crypto-vwap-bot:
    build: .
    container_name: discord-crypto-vwap-tool
    volumes:
      - ./config.py:/app/config.py
    restart: unless-stopped
    dns:
      - 127.0.0.1